title: "Futureal"
description: "Official Futureal game website"
footer: "(c) GREAT DNG 2022-2024"
header_pages:
    - index.md
    - download.md
    - docs.md
    - about.md

listen_for_clients_preferred_style: true
