title: "Futureal"
description: "Futureal website"
footer: "Futureal (c) GREAT DNG 2022-2023"
header_pages:
    - futureal.md
    - download.md
    - about.md

listen_for_clients_preferred_style: true

remote_theme: b2a3e8/jekyll-theme-console
